In [1]:
import numpy as np
import pandas as pd


In [2]:
! ls datasets

'breast cancer'   ecoli   glass   iris	 wine   zoo


ecoli dataset

In [3]:
df_ecoli = pd.read_csv('datasets/ecoli/ecoli-Copy1.data', header=None)
df_ecoli

0     1     2     3    4     5     6     7   8
0     AAT_ECOLI  0.49  0.29  0.48  0.5  0.56  0.24  0.35  cp
1    ACEA_ECOLI  0.07  0.40  0.48  0.5  0.54  0.35  0.44  cp
2    ACEK_ECOLI  0.56  0.40  0.48  0.5  0.49  0.37  0.46  cp
3    ACKA_ECOLI  0.59  0.49  0.48  0.5  0.52  0.45  0.36  cp
4     ADI_ECOLI  0.23  0.32  0.48  0.5  0.55  0.25  0.35  cp
..          ...   ...   ...   ...  ...   ...   ...   ...  ..
331  TREA_ECOLI  0.74  0.56  0.48  0.5  0.47  0.68  0.30  pp
332  UGPB_ECOLI  0.71  0.57  0.48  0.5  0.48  0.35  0.32  pp
333  USHA_ECOLI  0.61  0.60  0.48  0.5  0.44  0.39  0.38  pp
334  XYLF_ECOLI  0.59  0.61  0.48  0.5  0.42  0.42  0.37  pp
335  YTFQ_ECOLI  0.74  0.74  0.48  0.5  0.31  0.53  0.52  pp

[336 rows x 9 columns]

In [4]:
X_ecoli = df_ecoli.values[:, 1:-1]
np.savetxt('datasets/ecoli/X.csv', X_ecoli, fmt= '%.2f', delimiter=',')

In [5]:
y_ecoli = df_ecoli.values[:, -1]

classes_ecoli = sorted(list(set(y_ecoli)))
class_to_id_ecoli = {}
for i, cl in enumerate(classes_ecoli):
    class_to_id_ecoli[cl] = i + 1
print(class_to_id_ecoli)

for i in range(len(y_ecoli)):
    y_ecoli[i] = class_to_id_ecoli[y_ecoli[i]]

np.savetxt('datasets/ecoli/y.csv', y_ecoli, fmt='%i', delimiter=',')


{'cp': 1, 'im': 2, 'imL': 3, 'imS': 4, 'imU': 5, 'om': 6, 'omL': 7, 'pp': 8}


glass dataset

In [6]:
df_glass = pd.read_csv('datasets/glass/glass.data', header=None)
df_glass

0        1      2     3     4      5     6     7     8    9   10
0      1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0   1
1      2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0   1
2      3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0   1
3      4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0   1
4      5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0   1
..   ...      ...    ...   ...   ...    ...   ...   ...   ...  ...  ..
209  210  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0   7
210  211  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0   7
211  212  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0   7
212  213  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0   7
213  214  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0   7

[214 rows x 11 columns]

In [7]:
X_glass = df_glass.values[:, 1:-1]
np.savetxt('datasets/glass/X.csv', X_glass, fmt='%.5f', delimiter=',')

In [8]:
y_glass = df_glass.values[:, -1].astype(int)
np.savetxt('datasets/glass/y.csv', y_glass, fmt='%i', delimiter=',')

iris dataset

In [9]:
df_iris = pd.read_csv('datasets/iris/iris.data', header=None)
df_iris

0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [10]:
X_iris = df_iris.values[:, :-1]
np.savetxt('datasets/iris/X.csv', X_iris, fmt='%.1f', delimiter=',')

In [11]:
y_iris = df_iris.values[:, -1]

classes_iris = sorted(list(set(y_iris)))
class_to_id_iris = {}
for i, cl in enumerate(classes_iris):
    class_to_id_iris[cl] = i + 1
print(class_to_id_iris)

for i in range(len(y_iris)):
    y_iris[i] = class_to_id_iris[y_iris[i]]

np.savetxt('datasets/iris/y.csv', y_iris, fmt='%i', delimiter=',')


{'Iris-setosa': 1, 'Iris-versicolor': 2, 'Iris-virginica': 3}


wine dataset

In [12]:
df_wine = pd.read_csv('datasets/wine/wine.data', header=None)
df_wine

0      1     2     3     4    5     6     7     8     9      10    11  \
0     1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04   
1     1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
2     1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
3     1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
4     1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
..   ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
173   3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
174   3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
175   3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
176   3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
177   3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

       12    13  
0    3.92  1065  
1    3.40  1050  
2    3.17  1185  
3    3.45  1480  
4    2.93   735  
..    ...   ...  
173  1.74   740  
174  1.56   750  
175  1.56   835  
176  1.62   840  
177  1.60   560  

[178 rows x 14 columns]

In [13]:
X_wine = df_wine.values[:, 1:]
np.savetxt('datasets/wine/X.csv', X_wine, fmt='%.2f', delimiter=',')

In [14]:
y_wine = df_wine.values[:, 0].astype(int)
np.savetxt('datasets/wine/y.csv', y_wine, fmt='%i', delimiter=',')

zoo dataset

In [15]:
df_zoo = pd.read_csv('datasets/zoo/zoo.data', header=None)
df_zoo

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
0    aardvark   1   0   0   1   0   0   1   1   1   1   0   0   4   0   0   1   
1    antelope   1   0   0   1   0   0   0   1   1   1   0   0   4   1   0   1   
2        bass   0   0   1   0   0   1   1   1   1   0   0   1   0   1   0   0   
3        bear   1   0   0   1   0   0   1   1   1   1   0   0   4   0   0   1   
4        boar   1   0   0   1   0   0   1   1   1   1   0   0   4   1   0   1   
..        ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..   
96    wallaby   1   0   0   1   0   0   0   1   1   1   0   0   2   1   0   1   
97       wasp   1   0   1   0   1   0   0   0   0   1   1   0   6   0   0   0   
98       wolf   1   0   0   1   0   0   1   1   1   1   0   0   4   1   0   1   
99       worm   0   0   1   0   0   0   0   0   0   1   0   0   0   0   0   0   
100      wren   0   1   1   0   1   0   0   0   1   1   0   0   2   1   0   0   

     17  
0     1  
1     1  
2     4  
3     1  
4     1  
..   ..  
96    1  
97    6  
98    1  
99    7  
100   2  

[101 rows x 18 columns]

In [16]:
X_zoo = df_zoo.values[:, 1:-1]
np.savetxt('datasets/zoo/X.csv', X_zoo, fmt='%i', delimiter=',')

In [17]:
y_zoo = df_zoo.values[:, -1].astype(int)
np.savetxt('datasets/zoo/y.csv', y_zoo, fmt='%i', delimiter=',')

breast cancer

In [18]:
df_bc = pd.read_csv('datasets/breast cancer/breast-cancer.data', header=None)
df_bc

0      1        2      3    4   5  6      7  \
0    no-recurrence-events  30-39  premeno  30-34  0-2  no  3   left   
1    no-recurrence-events  40-49  premeno  20-24  0-2  no  2  right   
2    no-recurrence-events  40-49  premeno  20-24  0-2  no  2   left   
3    no-recurrence-events  60-69     ge40  15-19  0-2  no  2  right   
4    no-recurrence-events  40-49  premeno    0-4  0-2  no  2  right   
..                    ...    ...      ...    ...  ...  .. ..    ...   
281     recurrence-events  30-39  premeno  30-34  0-2  no  2   left   
282     recurrence-events  30-39  premeno  20-24  0-2  no  3   left   
283     recurrence-events  60-69     ge40  20-24  0-2  no  1  right   
284     recurrence-events  40-49     ge40  30-34  3-5  no  3   left   
285     recurrence-events  50-59     ge40  30-34  3-5  no  3   left   

             8    9  
0     left_low   no  
1     right_up   no  
2     left_low   no  
3      left_up   no  
4    right_low   no  
..         ...  ...  
281    left_up   no  
282    left_up  yes  
283    left_up   no  
284   left_low   no  
285   left_low   no  

[286 rows x 10 columns]

In [19]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [20]:
X_bc = np.zeros((len(df_bc), 16))

In [21]:
def sort_key(x):
    if x == 'no':
        return -1
    elif x == '?':
        return 0
    elif x == 'yes':
        return 1
    elif x is None:
        return 0
    elif type(x) is str:
        s = x.split('-')[0]
        if s.isnumeric():
            return int(s)
        else:
            return x
    else:
        return x

columns = [1, 3, 4, 5, 6, 7, 9]
for j, col in enumerate(columns):
    values = sorted(list(set(df_bc[col])), key=sort_key)
    value_to_num = {}
    for i, v in enumerate(values):
        value_to_num[v] = i + 1
    print('column #{}: {}'.format(col, value_to_num))
    for i in range(len(X_bc)):
        X_bc[i, j] = value_to_num[df_bc.loc[i][col]]

ohe_28 = pd.get_dummies(df_bc[[2, 8]])
X_bc[:, 7:] = ohe_28.values
print(X_bc)

column #1: {'20-29': 1, '30-39': 2, '40-49': 3, '50-59': 4, '60-69': 5, '70-79': 6}
column #3: {'0-4': 1, '5-9': 2, '10-14': 3, '15-19': 4, '20-24': 5, '25-29': 6, '30-34': 7, '35-39': 8, '40-44': 9, '45-49': 10, '50-54': 11}
column #4: {'0-2': 1, '3-5': 2, '6-8': 3, '9-11': 4, '12-14': 5, '15-17': 6, '24-26': 7}
column #5: {'no': 1, '?': 2, 'yes': 3}
column #6: {1: 1, 2: 2, 3: 3}
column #7: {'left': 1, 'right': 2}
column #9: {'no': 1, 'yes': 2}
[[2. 7. 1. ... 0. 0. 0.]
 [3. 5. 1. ... 0. 0. 1.]
 [3. 5. 1. ... 0. 0. 0.]
 ...
 [5. 5. 1. ... 1. 0. 0.]
 [3. 7. 2. ... 0. 0. 0.]
 [4. 7. 2. ... 0. 0. 0.]]


In [22]:
np.savetxt('datasets/breast cancer/X.csv', X_bc, '%i', delimiter=',')

In [23]:
y_bc = df_bc.values[:, 0]

classes_bc = sorted(list(set(y_bc)))
class_to_id_bc = {}
for i, cl in enumerate(classes_bc):
    class_to_id_bc[cl] = i + 1
print(class_to_id_bc)

for i in range(len(y_bc)):
    y_bc[i] = class_to_id_bc[y_bc[i]]

np.savetxt('datasets/breast cancer/y.csv', y_bc, fmt='%i', delimiter=',')

{'no-recurrence-events': 1, 'recurrence-events': 2}
